name: Build insert.so

on:
  push:
    branches:
      - main
    paths:
      - 'insert.c'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y gcc

      - name: Compile insert.c to insert.so
        run: |
          gcc -fPIC -shared -o insert.so insert.c

      - name: Upload insert.so as artifact
        uses: actions/upload-artifact@v3
        with:
          name: insert-so
          path: insert.so
